name: CI main branch flashcard model repository

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  continuous_integration_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Run unit tests
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r env/requirements.txt

      # Run unit tests
      - name: Run unit tests
        run: |
           python -m unittest discover -s tests -v